'''
This is the order that the colleges will appear by default
'''

customOrder = [
  'University of Maryland-College Park',
  'Harvard University',
  'Oregon State University',
  'Yale University',
  'Stanford University',
  'Massachusetts Institute of Technology',
  'United States Air Force Academy',
  'University of California-Berkeley',
  'Columbia University in the City of New York',
  'University of Washington-Seattle Campus',
  'California Institute of Technology',
  'Purdue University-Main Campus',
  'University of California-Los Angeles',
  'Northwestern University',
  'University of Illinois Urbana-Champaign',
  'University of Pennsylvania',
  'University of Wisconsin-Madison',
  'Carnegie Mellon University',
  'Ohio State University-Main Campus',
  'Williams College',
  'Georgia Institute of Technology-Main Campus',
  'University of Michigan-Ann Arbor',
  'Harvey Mudd College',
  'University of Southern California',
  'University of Oregon',
  'Princeton University',
  'Cornell University',
  'Johns Hopkins University',
  'The University of Texas at Austin',
  'Duke University',
  'University of California-San Diego',
  'University of Colorado Boulder',
  'University of Florida',
  'Brown University',
  'Amherst College',
  'University of California-Irvine',
  'University of North Carolina at Chapel Hill',
  'Rice University',
  'University of Arizona',
  'Northeastern University',
  'Tufts University',
  'United States Military Academy',
  'University of Virginia-Main Campus',
  'United States Naval Academy',
  'Vanderbilt University',
  'Emory University',
  'Dartmouth College',
  'University of California-Davis',
  'Washington University in St Louis',
  'University of Minnesota-Twin Cities',
  'University of Chicago',
  'New York University',
  'Georgetown University',
  'University of California-Santa Barbara',
  'University of Notre Dame'
]
